FROM prefecthq/prefect:3.4.25-python3.12

# Install git (lightdash sync)
RUN apt-get update && apt-get install -y git && apt-get clean

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /opt/prefect

COPY prefect.yaml /opt/prefect/prefect.yaml
COPY prefect/ /opt/prefect/prefect/

CMD ["prefect", "worker", "start", "--pool", "default-pool"]