FROM node:20-slim

WORKDIR /evidence

COPY ./evidence/package.json .

RUN rm -f package-lock.json

ENV NODE_OPTIONS=--max-old-space-size=900
RUN npm install --no-audit --no-fund --legacy-peer-deps
RUN npm rebuild sqlite3
RUN npm install -g serve

COPY ./evidence/ .

EXPOSE 3000

CMD ["/bin/sh", "-c", "mkdir -p /evidence/sources/analytics/data && ln -sf /data/analytics.duckdb /evidence/sources/analytics/data/analytics.duckdb && npm run sources && npm run build && serve build -p 3000"]
