#!/bin/sh
set -e

LIGHTDASH_URL="${LIGHTDASH_URL:-http://lightdash:8080}"
COOKIE_JAR="/tmp/lightdash-cookies.txt"

if [ -z "$LIGHTDASH_API_KEY" ]; then
  echo "==> No LIGHTDASH_API_KEY — running first-boot registration..."

  echo "    Step 1: Register user..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user" \
    -H "Content-Type: application/json" \
    -d "{\"firstName\":\"Admin\",\"lastName\":\"User\",\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null \
    && echo "         User registered." \
    || echo "         User already exists."

  echo "    Step 2: Create organisation..."
  curl -sf -b "$COOKIE_JAR" -X PUT "${LIGHTDASH_URL}/api/v1/org" \
    -H "Content-Type: application/json" \
    -d '{"name":"Analytics"}' \
    -o /dev/null

  echo "    Step 3: Re-login to refresh session with org context..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null

  echo "    Step 4: Create personal access token..."
  PAT_RESPONSE=$(curl -sf -b "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user/me/personal-access-tokens" \
    -H "Content-Type: application/json" \
    -d '{"description":"deploy-token","expiresAt":null,"autoGenerated":false}')

  LIGHTDASH_API_KEY=$(echo "$PAT_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['results']['token'])")
  echo "         Token: ${LIGHTDASH_API_KEY}"
fi

echo "==> Logging in to Lightdash CLI..."
lightdash login "${LIGHTDASH_URL}" --token "$LIGHTDASH_API_KEY"

echo "==> Deploying dbt project to Lightdash..."
lightdash deploy \
  --create "Analytics" \
  --assume-yes \
  --non-interactive \
  --project-dir /dbt \
  --profiles-dir /dbt

echo "==> Done."
