#!/bin/sh
set -e

LIGHTDASH_URL="${LIGHTDASH_URL:-http://lightdash:8080}"
COOKIE_JAR="/tmp/lightdash-cookies.txt"

if [ -z "$LIGHTDASH_API_KEY" ]; then
  echo "==> No LIGHTDASH_API_KEY — running first-boot registration..."

  echo "    Step 1: Register user..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user" \
    -H "Content-Type: application/json" \
    -d "{\"firstName\":\"Admin\",\"lastName\":\"User\",\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null \
    && echo "         User registered." \
    || {
      echo "         User already exists — logging in to get session cookie..."
      curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/login" \
        -H "Content-Type: application/json" \
        -d "{\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
        -o /dev/null
    }

  echo "    Step 2: Create organisation (skip if already exists)..."
  curl -s -b "$COOKIE_JAR" -X PUT "${LIGHTDASH_URL}/api/v1/org" \
    -H "Content-Type: application/json" \
    -d '{"name":"Analytics"}' \
    -o /dev/null || true

  echo "    Step 3: Re-login to refresh session with org context..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null

  echo "    Step 4: Create personal access token..."
  PAT_RESPONSE=$(curl -sf -b "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user/me/personal-access-tokens" \
    -H "Content-Type: application/json" \
    -d '{"description":"deploy-token","expiresAt":null,"autoGenerated":false}')

  LIGHTDASH_API_KEY=$(echo "$PAT_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['results']['token'])")

  echo ""
  echo "================================================================"
  echo "  LIGHTDASH_API_KEY=${LIGHTDASH_API_KEY}"
  echo "  Copy this token and set it as an env var in Coolify / .env"
  echo "  then restart the vanna service."
  echo "================================================================"
  echo ""
fi

echo "==> Logging in to Lightdash CLI..."
lightdash login "${LIGHTDASH_URL}" --token "$LIGHTDASH_API_KEY"

# Reuse existing project instead of creating a duplicate on every run
echo "==> Checking for existing Lightdash project..."
PROJECT_UUID=$(curl -s -H "Authorization: ApiKey ${LIGHTDASH_API_KEY}" \
  "${LIGHTDASH_URL}/api/v1/org/projects" \
  | python3 -c "
import sys, json
projects = json.load(sys.stdin).get('results', [])
real = [p for p in projects if not p.get('type','').startswith('preview')]
print(real[0]['projectUuid'] if real else '')
" 2>/dev/null || echo "")

if [ -n "$PROJECT_UUID" ]; then
  echo "    Reusing existing project: $PROJECT_UUID"
  lightdash config set-project --uuid "$PROJECT_UUID"
  lightdash deploy \
    --assume-yes \
    --non-interactive \
    --project-dir /dbt \
    --profiles-dir /dbt
else
  echo "    No existing project — creating Analytics..."
  lightdash deploy \
    --create "Analytics" \
    --assume-yes \
    --non-interactive \
    --project-dir /dbt \
    --profiles-dir /dbt
fi

# Upload dashboard YAML files (content-as-code)
if [ -d "/dbt/lightdash/charts" ] || [ -d "/dbt/lightdash/dashboards" ]; then
  echo "==> Uploading dashboard YAML files..."
  lightdash upload --force --path /dbt/lightdash --include-charts
else
  echo "==> No dashboard YAML files — skipping upload."
fi

echo "==> Done."
