#!/bin/sh
# Errors are logged but never cause exit 1 — Coolify must not fail the deployment
# because of this init container.

LIGHTDASH_URL="${LIGHTDASH_URL:-http://lightdash:8080}"
COOKIE_JAR="/tmp/lightdash-cookies.txt"

# Ensure bi_readonly user exists with the correct password
echo "==> Provisioning bi_readonly DB user..."
python3 - <<'PYEOF'
import os, sys
try:
    import psycopg2
    conn = psycopg2.connect(
        host=os.environ['ANALYTICS_DB_HOST'],
        port=int(os.environ.get('ANALYTICS_DB_PORT', 5432)),
        dbname=os.environ['ANALYTICS_DB_NAME'],
        user=os.environ['ANALYTICS_DB_ADMIN_USER'],
        password=os.environ['ANALYTICS_DB_ADMIN_PASSWORD'],
    )
    conn.autocommit = True
    cur = conn.cursor()
    password = os.environ['ANALYTICS_DB_PASSWORD']
    cur.execute("SELECT 1 FROM pg_roles WHERE rolname='bi_readonly'")
    if cur.fetchone():
        cur.execute("ALTER USER bi_readonly WITH PASSWORD %s", (password,))
        print("    bi_readonly password synced.")
    else:
        cur.execute("CREATE USER bi_readonly WITH PASSWORD %s", (password,))
        cur.execute("GRANT CONNECT ON DATABASE analytics TO bi_readonly")
        cur.execute("GRANT pg_read_all_data TO bi_readonly")
        print("    bi_readonly created.")
    conn.close()
except Exception as e:
    print(f"    WARNING: could not provision bi_readonly: {e}")
PYEOF

if [ -z "$LIGHTDASH_API_KEY" ]; then
  echo "==> No LIGHTDASH_API_KEY — running first-boot registration..."

  echo "    Step 1: Register user..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user" \
    -H "Content-Type: application/json" \
    -d "{\"firstName\":\"Admin\",\"lastName\":\"User\",\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null \
    && echo "         User registered." \
    || {
      echo "         User already exists — logging in to get session cookie..."
      curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/login" \
        -H "Content-Type: application/json" \
        -d "{\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
        -o /dev/null || echo "         WARNING: login failed"
    }

  echo "    Step 2: Create organisation (skip if already exists)..."
  curl -s -b "$COOKIE_JAR" -X PUT "${LIGHTDASH_URL}/api/v1/org" \
    -H "Content-Type: application/json" \
    -d '{"name":"Analytics"}' \
    -o /dev/null || true

  echo "    Step 3: Re-login to refresh session with org context..."
  curl -sf -c "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${LIGHTDASH_EMAIL}\",\"password\":\"${LIGHTDASH_PASSWORD}\"}" \
    -o /dev/null || echo "    WARNING: re-login failed"

  echo "    Step 4: Create personal access token..."
  PAT_RESPONSE=$(curl -sf -b "$COOKIE_JAR" -X POST "${LIGHTDASH_URL}/api/v1/user/me/personal-access-tokens" \
    -H "Content-Type: application/json" \
    -d '{"description":"deploy-token","expiresAt":null,"autoGenerated":false}' || echo "")

  if [ -n "$PAT_RESPONSE" ]; then
    LIGHTDASH_API_KEY=$(echo "$PAT_RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin)['results']['token'])" 2>/dev/null || echo "")
  fi

  if [ -n "$LIGHTDASH_API_KEY" ]; then
    echo ""
    echo "================================================================"
    echo "  LIGHTDASH_API_KEY=${LIGHTDASH_API_KEY}"
    echo "  Copy this token and set it as an env var in Coolify / .env"
    echo "  then restart the vanna service."
    echo "================================================================"
    echo ""
  else
    echo "    WARNING: could not obtain PAT — set LIGHTDASH_API_KEY manually after registering via the UI."
    echo "==> Exiting — nothing to deploy without a valid API key."
    exit 0
  fi
fi

echo "==> Logging in to Lightdash CLI..."
if ! lightdash login "${LIGHTDASH_URL}" --token "$LIGHTDASH_API_KEY"; then
  echo "ERROR: lightdash login failed — token may be invalid. Set LIGHTDASH_API_KEY in Coolify and redeploy."
  exit 0
fi

# Reuse existing project instead of creating a duplicate on every run
echo "==> Checking for existing Lightdash project..."
PROJECT_UUID=$(curl -s -H "Authorization: ApiKey ${LIGHTDASH_API_KEY}" \
  "${LIGHTDASH_URL}/api/v1/org/projects" \
  | python3 -c "
import sys, json
projects = json.load(sys.stdin).get('results', [])
real = [p for p in projects if not p.get('type','').startswith('preview')]
print(real[0]['projectUuid'] if real else '')
" 2>/dev/null || echo "")

if [ -n "$PROJECT_UUID" ]; then
  echo "    Reusing existing project: $PROJECT_UUID"
  lightdash config set-project --uuid "$PROJECT_UUID"
  lightdash deploy \
    --assume-yes \
    --non-interactive \
    --ignore-errors \
    --project-dir /dbt \
    --profiles-dir /dbt || echo "WARNING: lightdash deploy failed"
else
  echo "    No existing project — creating Analytics..."
  lightdash deploy \
    --create "Analytics" \
    --assume-yes \
    --non-interactive \
    --ignore-errors \
    --project-dir /dbt \
    --profiles-dir /dbt || echo "WARNING: lightdash deploy failed"

  # After creation, fetch the new project UUID and select it so upload works
  PROJECT_UUID=$(curl -s -H "Authorization: ApiKey ${LIGHTDASH_API_KEY}" \
    "${LIGHTDASH_URL}/api/v1/org/projects" \
    | python3 -c "
import sys, json
projects = json.load(sys.stdin).get('results', [])
real = [p for p in projects if not p.get('type','').startswith('preview')]
print(real[0]['projectUuid'] if real else '')
" 2>/dev/null || echo "")

  if [ -n "$PROJECT_UUID" ]; then
    echo "    Project created: $PROJECT_UUID"
    lightdash config set-project --uuid "$PROJECT_UUID"
  fi
fi

# Upload dashboard YAML files (content-as-code)
if [ -d "/dbt/lightdash/charts" ] || [ -d "/dbt/lightdash/dashboards" ]; then
  echo "==> Uploading dashboard YAML files..."
  lightdash upload --force --path /dbt/lightdash --include-charts || echo "WARNING: lightdash upload failed"
else
  echo "==> No dashboard YAML files — skipping upload."
fi

echo "==> Done."
