name: Total Revenue
description: Total Revenue
tableName: high_value_customer_churn
updatedAt: '2026-04-04T03:08:42.000Z'
metricQuery:
  exploreName: high_value_customer_churn
  dimensions: []
  metrics:
  - high_value_customer_churn_total_revenue_sum
  filters: {}
  sorts: []
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    bigNumber: high_value_customer_churn_total_revenue_sum
    bigNumberLabel: Total Revenue
slug: total_revenue
tableConfig:
  columnOrder:
  - high_value_customer_churn_total_revenue_sum
spaceSlug: home
version: 1
