name: Total Revenue by Category
description: Total Revenue by Category
tableName: high_value_customer_churn
updatedAt: '2026-04-04T03:08:42.000Z'
metricQuery:
  exploreName: high_value_customer_churn
  dimensions:
  - high_value_customer_churn_category
  metrics: &id001
  - high_value_customer_churn_total_revenue_sum
  filters: {}
  sorts:
  - fieldId: high_value_customer_churn_total_revenue_sum
    descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: high_value_customer_churn_category
      yField: *id001
    eChartsConfig:
      axes:
      - position: bottom
      - position: left
        name: Total Revenue
      series:
      - type: bar
        name: Total Revenue
        encode:
          xRef:
            field: high_value_customer_churn_category
          yRef:
            field: high_value_customer_churn_total_revenue_sum
slug: total_revenue_by_category
tableConfig:
  columnOrder:
  - high_value_customer_churn_category
  - high_value_customer_churn_total_revenue_sum
spaceSlug: home
version: 1
